apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
  namespace: dev
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/local/mohsen2"
